### ISSUE TITLE
10 results

### ISSUE THREAD

**Issue by Joseph65** [Cloud-Player/web#44]
When i search something on https://cloud-player.io it only shows 10 results
im on firefox 57, also it would be nice to have more sort options like month, week, year.

**Comment by Zarlex** [comment]
Thanks for reporting the bug. The firefox issue will be fixed with the next version.
In case you don't want to wait you can give our native client a try: https://github.com/Cloud-Player/desktop-app/releases/tag/v1.0.0 (available for windows and mac)

Regarding the sort options i will think of something.
